services:
  tun2proxy-1:
    image: ghcr.io/tun2proxy/tun2proxy-ubuntu:latest
    container_name: tun2proxy-1
    volumes:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.default.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    command: --proxy socks5://user:pass@ip:port --dns virtual
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cat", "/proc/net/dev"]
      interval: 2s
      timeout: 2s
      retries: 10

  ubuntu-1:
    build: .
    network_mode: "container:tun2proxy-1"
    stdin_open: true
    tty: true
    depends_on:
      tun2proxy-1:
        condition: service_healthy
    restart: on-failure
